services:
  mongo:
    image: mongo:7
    container_name: quiz_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: quiz_backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/quizplatform
      - JWT_SECRET=supersecretjwtkey_quizplatform_2026_secure
      - JWT_EXPIRES_IN=8h
      - SEED_ADMIN_PASSWORD=ChangeMe123!
      - CORS_ORIGIN=http://localhost:5173
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: quiz_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo_data:
